name: Upgrade NPM packages

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  upgrade-packages:
    name: Upgrade packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Upgrade packages 🔀
        run: npx npm-check-updates -u
        
      - name: Install new packages 🔀
        run: npm i

      - name: Commit and create PR 🔀
        uses: peter-evans/create-pull-request@v3
        with:
          title: "build(deps): Upgrade NPM packages (automated)"
          branch: "build-deps-upgrade-npm-packages-automated"
          commit-message: "build(deps): upgrade NPM packages (automated)"
          committer: "GitHub <noreply@github.com>"
          delete-branch: "true"
          base: "main"
